apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mfstaticweb-route
  namespace: mfweb1
  labels:
    razee/watch-resource: lite
spec:
  path: "/"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: mfstaticweb-svc
